// Generated by https://github.com/gamous/FFXIVNetworkOpcodes
namespace FFXIVOpcodes.Global
{
    public enum ServerLobbyIpcType : ushort
    {
    
    };
    
    public enum ClientLobbyIpcType : ushort
    {
    
    };
    
    public enum ServerZoneIpcType : ushort
    {
        ActorCast = 0x029C,
        ActorControl = 0x0179,
        ActorControlSelf = 0x026F,
        ActorControlTarget = 0x0220,
        ActorGauge = 0x0171,
        ActorMove = 0x01DB,
        ActorSetPos = 0x018C,
        Effect = 0x01C9,
        AoeEffect8 = 0x024A,
        AoeEffect16 = 0x038A,
        AoeEffect24 = 0x00C8,
        AoeEffect32 = 0x032B,
        BossStatusEffectList = 0x01EE,
        CFPreferredRole = 0x00DE,
        CompanyAirshipStatus = 0x026B,
        CompanySubmersibleStatus = 0x0103,
        ContentFinderNotifyPop = 0x038B,
        EffectResult = 0x022C,
        EffectResult4 = 0x01B6,
        EffectResult8 = 0x016E,
        EffectResult16 = 0x0250,
        EffectResultBasic = 0x0384,
        EffectResultBasic4 = 0x0121,
        EffectResultBasic8 = 0x01D7,
        EffectResultBasic16 = 0x03D9,
        EffectResultBasic32 = 0x0332,
        EffectResultBasic64 = 0x0275,
        EventFinish = 0x0194,
        EventPlay = 0x02DE,
        EventPlay4 = 0x0317,
        EventPlay8 = 0x01CD,
        EventPlay16 = 0x01FE,
        EventPlay32 = 0x02FC,
        EventPlay64 = 0x007C,
        EventPlay128 = 0x0337,
        EventPlay255 = 0x01D2,
        EventStart = 0x01A1,
        Examine = 0x01BC,
        ExamineSearchInfo = 0x030E,
        InitZone = 0x0222,
        InventoryActionAck = 0x01EB,
        MarketBoardItemListing = 0x02F1,
        MarketBoardItemListingCount = 0x00AA,
        MarketBoardItemListingHistory = 0x00A8,
        MarketBoardSearchResult = 0x021E,
        NpcSpawn = 0x039E,
        NpcSpawn2 = 0x02E5,
        ObjectSpawn = 0x031B,
        PlaceFieldMarker = 0x038E,
        PlaceFieldMarkerPreset = 0x0204,
        PlayerSetup = 0x02B3,
        PlayerSpawn = 0x007F,
        PlayerStats = 0x01B8,
        Playtime = 0x0326,
        PrepareZoning = 0x0195,
        SystemLogMessage = 0x009A,
        StatusEffectList = 0x02BC,
        StatusEffectList2 = 0x0164,
        StatusEffectList3 = 0x024C,
        UpdateClassInfo = 0x02EC,
        UpdateHpMpTp = 0x0383,
        UpdateInventorySlot = 0x010E,
        UpdateSearchInfo = 0x034A,
        WardLandInfo = 0x00E4,
        CEDirector = 0x00B8,
        Logout = 0x01D0,
        MarketBoardPurchase = 0x032F,
        AirshipStatusList = 0x0070,
        AirshipStatus = 0x0142,
        SubmarineProgressionStatus = 0x0148,
        SubmarineStatusList = 0x0232,
        FreeCompanyInfo = 0x01DD,
        AirshipExplorationResult = 0x034F,
        SubmarineExplorationResult = 0x01A8,
        FreeCompanyDialog = 0x00E6,
        FateInfo = 0x0187,
        EnvironmentControl = 0x02CE,
        UpdateRecastTimes = 0x01B9,
        UpdateHate = 0x0134,
        UpdateHater = 0x02F9,
        SocialList = 0x01F1,
        IslandWorkshopSupplyDemand = 0x039B,
    };
    
    public enum ClientLobbyIpcType : ushort
    {
        ActionRequest = 0x0249,
        ActionRequestGroundTargeted = 0x03DC,
        ChatHandler = 0x02C6,
        ClientTrigger  = 0x0174,
        InventoryModifyHandler = 0x008F,
        MarketBoardPurchaseHandler = 0x0095,
        SetSearchInfoHandler = 0x0227,
        UpdatePositionHandler = 0x010F,
        UpdatePositionInstance = 0x00DB,
    };
    
    public enum ServerChatIpcType : ushort
    {
    
    };
    
    public enum ClientChatIpcType : ushort
    {
    
    };
    
}
