// Generated by https://github.com/gamous/FFXIVNetworkOpcodes
namespace FFXIVOpcodes.Global
{
    public enum ServerLobbyIpcType : ushort
    {
    
    };
    
    public enum ClientLobbyIpcType : ushort
    {
    
    };
    
    public enum ServerZoneIpcType : ushort
    {
        ActorCast = 0x02AD,
        ActorControl = 0x0197,
        ActorControlSelf = 0x0238,
        ActorControlTarget = 0x028B,
        ActorGauge = 0x0382,
        ActorMove = 0x0384,
        ActorSetPos = 0x0329,
        Effect = 0x0395,
        AoeEffect8 = 0x0311,
        AoeEffect16 = 0x0351,
        AoeEffect24 = 0x03C2,
        AoeEffect32 = 0x006A,
        BossStatusEffectList = 0x034D,
        CompanyAirshipStatus = 0x02DE,
        CompanySubmersibleStatus = 0x02A3,
        ContentFinderNotifyPop = 0x0173,
        EffectResult = 0x01F0,
        EffectResult4 = 0x0169,
        EffectResult8 = 0x00B9,
        EffectResult16 = 0x024D,
        EffectResultBasic = 0x037E,
        EffectResultBasic4 = 0x0077,
        EffectResultBasic8 = 0x029F,
        EffectResultBasic16 = 0x0208,
        EffectResultBasic32 = 0x01C2,
        EffectResultBasic64 = 0x0220,
        EventPlay = 0x038C,
        EventPlay4 = 0x0274,
        EventPlay8 = 0x02D9,
        EventPlay16 = 0x01AB,
        EventPlay32 = 0x0203,
        EventPlay64 = 0x038D,
        EventPlay128 = 0x035F,
        EventPlay255 = 0x011D,
        EventStart = 0x0179,
        ExamineSearchInfo = 0x010F,
        MarketBoardItemListing = 0x0270,
        MarketBoardItemListingCount = 0x03C3,
        MarketBoardItemListingHistory = 0x036C,
        MarketBoardSearchResult = 0x02E1,
        NpcSpawn = 0x0359,
        NpcSpawn2 = 0x0190,
        ObjectSpawn = 0x0265,
        PlaceFieldMarker = 0x01D8,
        PlaceFieldMarkerPreset = 0x0332,
        PlayerSetup = 0x0091,
        PlayerSpawn = 0x00DD,
        PlayerStats = 0x0086,
        Playtime = 0x00E5,
        PrepareZoning = 0x02DB,
        SystemLogMessage = 0x0325,
        StatusEffectList = 0x019B,
        StatusEffectList2 = 0x00F8,
        StatusEffectList3 = 0x03CD,
        UpdateHpMpTp = 0x02A2,
        UpdateInventorySlot = 0x0308,
        UpdateSearchInfo = 0x02B6,
        WardLandInfo = 0x02D3,
        CEDirector = 0x025B,
        MarketBoardPurchase = 0x02E0,
        AirshipStatusList = 0x01F2,
        AirshipStatus = 0x032A,
        SubmarineProgressionStatus = 0x02C1,
        SubmarineStatusList = 0x009B,
        FreeCompanyInfo = 0x0273,
        AirshipExplorationResult = 0x010D,
        SubmarineExplorationResult = 0x0107,
        FreeCompanyDialog = 0x03E0,
        EnvironmentControl = 0x010C,
        UpdateRecastTimes = 0x00A9,
        UpdateHate = 0x0328,
        UpdateHater = 0x026C,
        SocialList = 0x0176,
    };
    
    public enum ClientLobbyIpcType : ushort
    {
        ActionRequest = 0x0093,
        ActionRequestGroundTargeted = 0x00EA,
        ChatHandler = 0x0316,
        ClientTrigger  = 0x0221,
        InventoryModifyHandler = 0x01E1,
        MarketBoardPurchaseHandler = 0x0336,
        SetSearchInfoHandler = 0x01A7,
        UpdatePositionHandler = 0x0392,
        UpdatePositionInstance = 0x02F8,
    };
    
    public enum ServerChatIpcType : ushort
    {
    
    };
    
    public enum ClientChatIpcType : ushort
    {
    
    };
    
}
