// Generated by https://github.com/gamous/FFXIVNetworkOpcodes
namespace FFXIVOpcodes.CN
{
    public enum ServerLobbyIpcType : ushort
    {
    
    };
    
    public enum ClientLobbyIpcType : ushort
    {
    
    };
    
    public enum ServerZoneIpcType : ushort
    {
        PlayerSpawn = 0x02B6,
        NpcSpawn = 0x011D,
        NpcSpawn2 = 0x0113,
        ActorFreeSpawn = 0x034A,
        ObjectSpawn = 0x00E3,
        ObjectDespawn = 0x03A9,
        CreateTreasure = 0x0212,
        OpenTreasure = 0x035F,
        TreasureFadeOut = 0x0116,
        ActorMove = 0x03B1,
        _record_unk10_ = 0x01AB,
        Transfer = 0x0377,
        Effect = 0x030F,
        AoeEffect8 = 0x0199,
        AoeEffect16 = 0x01E2,
        AoeEffect24 = 0x03B6,
        AoeEffect32 = 0x037E,
        ActorCast = 0x0186,
        ActorControl = 0x0365,
        ActorControlTarget = 0x015B,
        ActorControlSelf = 0x0245,
        DirectorVars = 0x00A2,
        ContentDirectorSync = 0x0316,
        _record_unk23_ = 0x017F,
        EnvironmentControl = 0x0309,
        _record_unk29_ = 0x0301,
        LandSetMap = 0x03A0,
        EventStart = 0x02A2,
        EventFinish = 0x0088,
        EventPlay = 0x0067,
        EventPlay4 = 0x018B,
        EventPlay8 = 0x007F,
        EventPlay16 = 0x0205,
        EventPlay32 = 0x01AE,
        EventPlay64 = 0x0259,
        EventPlay128 = 0x0101,
        EventPlay255 = 0x00C0,
        BattleTalk2 = 0x0067,
        BattleTalk4 = 0x018B,
        BattleTalk8 = 0x007F,
        BalloonTalk2 = 0x00BE,
        BalloonTalk4 = 0x0086,
        BalloonTalk8 = 0x009E,
        SystemLogMessage = 0x0110,
        SystemLogMessage32 = 0x014C,
        SystemLogMessage48 = 0x03DC,
        SystemLogMessage80 = 0x034D,
        SystemLogMessage144 = 0x035E,
        NpcYell = 0x0182,
        ActorSetPos = 0x01C4,
        PrepareZoning = 0x0202,
        StatusEffectList3 = 0x01DE,
        WeatherChange = 0x020B,
        UpdateParty = 0x01EF,
        UpdateAlliance = 0x02BD,
        UpdateSpAlliance = 0x00F8,
        UpdateHpMpTp = 0x0121,
        StatusEffectList = 0x01FE,
        EurekaStatusEffectList = 0x01A0,
        StatusEffectList2 = 0x0163,
        BossStatusEffectList = 0x02CA,
        EffectResult = 0x0200,
        EffectResult4 = 0x01A3,
        EffectResult8 = 0x0191,
        EffectResult16 = 0x02AF,
        PartyPos = 0x007B,
        AlliancePos = 0x0203,
        SpAlliancePos = 0x0394,
        PlaceMarker = 0x02D6,
        PlaceFieldMarkerPreset = 0x02C3,
        PlaceFieldMarker = 0x031D,
        ActorGauge = 0x034B,
        CharaVisualEffect = 0x03A8,
        Fall = 0x039F,
        UpdateHate = 0x0310,
        UpdateHater = 0x0293,
        FirstAttack = 0x018A,
        ModelEquip = 0x0065,
        EquipDisplayFlags = 0x0105,
        UnMount = 0x0345,
        Mount = 0x025E,
        PlayMotionSync = 0x01D4,
        CountdownInitiate = 0x0337,
        CountdownCancel = 0x0382,
        InitZone = 0x0356,
        Examine = 0x00ED,
        ExamineSearchInfo = 0x00B3,
        InventoryActionAck = 0x02E7,
        MarketBoardItemListing = 0x0069,
        MarketBoardItemListingCount = 0x007E,
        MarketBoardItemListingHistory = 0x0141,
        MarketBoardSearchResult = 0x0289,
        MarketBoardPurchase = 0x00FE,
        PlayerSetup = 0x0217,
        PlayerStats = 0x009B,
        Playtime = 0x0216,
        UpdateClassInfo = 0x0386,
        UpdateInventorySlot = 0x038E,
        UpdateSearchInfo = 0x03CC,
        WardLandInfo = 0x02F8,
        CEDirector = 0x008C,
        Logout = 0x01D6,
        FreeCompanyInfo = 0x00F1,
        FreeCompanyDialog = 0x032A,
        AirshipStatusList = 0x010E,
        AirshipStatus = 0x01D9,
        AirshipExplorationResult = 0x01ED,
        SubmarineStatusList = 0x00EB,
        SubmarineProgressionStatus = 0x02B2,
        SubmarineExplorationResult = 0x02A6,
        CFPreferredRole = 0x0160,
        CompanyAirshipStatus = 0x0272,
        CompanySubmersibleStatus = 0x026E,
        ContentFinderNotifyPop = 0x0171,
        FateInfo = 0x03D2,
        UpdateRecastTimes = 0x00B6,
        SocialList = 0x0368,
        IslandWorkshopSupplyDemand = 0x0201,
        RSV = 0x00C5,
        RSF = 0x02F6,
    };
    
    public enum ClientLobbyIpcType : ushort
    {
        ActionRequest = 0x0363,
        ActionRequestGroundTargeted = 0x03E1,
        ChatHandler = 0x014F,
        ClientTrigger  = 0x03AD,
        InventoryModifyHandler = 0x0257,
        MarketBoardPurchaseHandler = 0x0074,
        SetSearchInfoHandler = 0x0381,
        UpdatePositionHandler = 0x00D4,
        UpdatePositionInstance = 0x039A,
    };
    
    public enum ServerChatIpcType : ushort
    {
    
    };
    
    public enum ClientChatIpcType : ushort
    {
    
    };
    
}
