// Generated by https://github.com/gamous/FFXIVNetworkOpcodes
namespace FFXIVOpcodes.CN
{
    public enum ServerLobbyIpcType : ushort
    {
    
    };
    
    public enum ClientLobbyIpcType : ushort
    {
    
    };
    
    public enum ServerZoneIpcType : ushort
    {
        ActorCast = 0x033B,
        ActorControl = 0x0249,
        ActorControlSelf = 0x0397,
        ActorControlTarget = 0x01FF,
        ActorGauge = 0x022E,
        ActorMove = 0x00CE,
        ActorSetPos = 0x0084,
        Effect = 0x02E7,
        AoeEffect8 = 0x00EF,
        AoeEffect16 = 0x036F,
        AoeEffect24 = 0x03C4,
        AoeEffect32 = 0x02E6,
        BossStatusEffectList = 0x0391,
        CFPreferredRole = 0x01FB,
        CompanyAirshipStatus = 0x0180,
        CompanySubmersibleStatus = 0x0082,
        ContentFinderNotifyPop = 0x00CF,
        EffectResult = 0x030E,
        EffectResult4 = 0x02D9,
        EffectResult8 = 0x01FC,
        EffectResult16 = 0x018D,
        EventFinish = 0x01EC,
        EventPlay = 0x02BE,
        EventPlay4 = 0x02B5,
        EventPlay8 = 0x0173,
        EventPlay16 = 0x025A,
        EventPlay32 = 0x0312,
        EventPlay64 = 0x006A,
        EventPlay128 = 0x00A7,
        EventPlay255 = 0x00EE,
        EventStart = 0x02BB,
        Examine = 0x006D,
        ExamineSearchInfo = 0x0371,
        InitZone = 0x008B,
        InventoryActionAck = 0x030A,
        MarketBoardItemListing = 0x022B,
        MarketBoardItemListingCount = 0x03E4,
        MarketBoardItemListingHistory = 0x03BC,
        MarketBoardSearchResult = 0x01E4,
        NpcSpawn = 0x00E7,
        NpcSpawn2 = 0x018F,
        ObjectSpawn = 0x01D6,
        PlaceFieldMarker = 0x017B,
        PlaceFieldMarkerPreset = 0x00E5,
        PlayerSetup = 0x0178,
        PlayerSpawn = 0x029F,
        PlayerStats = 0x032A,
        Playtime = 0x012B,
        PrepareZoning = 0x03AC,
        StatusEffectList = 0x02F2,
        StatusEffectList2 = 0x00DA,
        StatusEffectList3 = 0x03CD,
        UpdateClassInfo = 0x00EC,
        UpdateHpMpTp = 0x0399,
        UpdateInventorySlot = 0x0350,
        UpdateSearchInfo = 0x008C,
        WardLandInfo = 0x02AD,
        CEDirector = 0x00E4,
        Logout = 0x00AF,
        MarketBoardPurchase = 0x0144,
        AirshipStatusList = 0x01AC,
        AirshipStatus = 0x017C,
        SubmarineProgressionStatus = 0x01A7,
        SubmarineStatusList = 0x0331,
        FreeCompanyInfo = 0x022F,
        AirshipExplorationResult = 0x012C,
        SubmarineExplorationResult = 0x01DE,
        FreeCompanyDialog = 0x00EB,
        FateInfo = 0x0208,
        EnvironmentControl = 0x024B,
        UpdateRecastTimes = 0x033E,
        UpdateHate = 0x0176,
        UpdateHater = 0x00DD,
        SocialList = 0x03E2,
        IslandWorkshopSupplyDemand = 0x01C1,
    };
    
    public enum ClientLobbyIpcType : ushort
    {
        ActionRequest = 0x0212,
        ActionRequestGroundTargeted = 0x0353,
        ChatHandler = 0x00B0,
        ClientTrigger  = 0x0387,
        InventoryModifyHandler = 0x0369,
        MarketBoardPurchaseHandler = 0x0383,
        SetSearchInfoHandler = 0x0151,
        UpdatePositionHandler = 0x0164,
        UpdatePositionInstance = 0x03B6,
    };
    
    public enum ServerChatIpcType : ushort
    {
    
    };
    
    public enum ClientChatIpcType : ushort
    {
    
    };
    
}
